### ISSUE TITLE
[HIPIFY] Isn't hipify-clang preprocessor based tool?

### ISSUE THREAD

**Issue by alvin546** [ROCm-Developer-Tools/HIPIFY#1131]
I have attempted to migrate below code using hipify-clang in Windows environment.
`#if 0
#include <mpi.h>
#else
#include <omp.h>
#endif

int main()
{
	//CUDA code
	return 0;
}`

But encountering following error:
`C:\Users\APENDLIX\AppData\Local\Temp\test.cu-10f48a.hip:16:10: fatal error: 'mpi.h' file not found
#include <mpi.h>
         ^~~~~~~
Exception Code: 0xC0000005`

I'm wondering about why it is considering mpi.h though it is disabled. Isn't hipify-clang preprocessor based tool? Am I missing anything to consider for migration?

**Comment by emankov** [comment]
hipify-clang is a clang frontend-based tool, which utilizes C/C++ preprocessor as well. By default, all preprocessor conditional branches are taken into account, because the main aim is to HIPIFY AMAP. 

This default behaviour can be turned off by providing `--default-preprocessor` option. 

For all available options, use `--help` option, please.

**Comment by alvin546** [comment]
Thank you, this option addressed my issue.
May I know what is HIPIFY AMAP?

**Comment by emankov** [comment]
I meant, to HIPIFY (CUDA sources) As Much As Possible.

**Comment by emankov** [comment]
Closing as answered.
