### ISSUE TITLE
[HIPIFY][CUDA] runtime error while hipifying a simple CUDA code

### ISSUE THREAD

**Issue by ytzhang1** [ROCm-Developer-Tools/HIPIFY#772]
Hi, I tried to migrate a simple CUDA code using hipify and llvm-15.0.7, but got the following error. Any idea why this happens ? Thanks,

llvm-15.0.7/install/lib/clang/15.0.7/include/__clang_cuda_texture_intrinsics.h:696:13: error: no template named 'texture'
            texture<__DataT, __TexT, cudaReadModeNormalizedFloat> __handle,
            ^
llvm-15.0.7/install/lib/clang/15.0.7/include/__clang_cuda_texture_intrinsics.h:709:13: error: no template named 'texture'
            texture<__DataT, __TexT, cudaReadModeElementType> __handle,

**Comment by emankov** [comment]
Most likely, the reported compilation errors are due to CUDA 12.0, which is not yet fully supported either by LLVM 15.x, or even by LLVM 16.x. The latest supported CUDA version for LLVM 15.x is 11.8.

Please, follow the instructions given at https://github.com/ROCm-Developer-Tools/HIPIFY#-hipify-clang-dependencies.

**Comment by ytzhang1** [comment]
Hi, I was using cuda 11.7 or 11.8 for the --cuda-path option, that doesn't seem an issue. But I updated the hipify repository today and rebuilt hipify, now the problem is gone. Thanks!
