### ISSUE TITLE
[HIPIFY] Conditional Pre-processor directives resulting in duplicate function declarations

### ISSUE THREAD

**Issue by twaters** [ROCm-Developer-Tools/HIPIFY#964]
I am attempting to hipify a generated header file (from MATLAB) creating a header that looks like the following:

```
#if defined(MW_GPU_MEMORY_MANAGER) && !defined(__CUDA_ARCH__)

template<typename MWType_>
cudaError_t mwCudaMalloc(MWType_** devPtr, size_t size) {
    gcmemory::MemoryManager& manager = gcmemory::getMemoryManager();
    return manager.allocate(devPtr, size, gcmemory::DISCRETE);
}

#else
#include "cuda_runtime.h"

template<typename MWType_>
__host__ __device__
cudaError_t mwCudaMalloc(MWType_** devPtr, size_t size) {
    return cudaMalloc(devPtr, size);
}
#endif
```

hipify results with the following duplicate-definition error:

```
/tmp/MWCudaMemoryFunctions.hpp-96bc82.hip:35:13: error: __host__ __device__ function 'mwCudaMalloc' cannot overload __host__ function 'mwCudaMalloc'
cudaError_t mwCudaMalloc(MWType_** devPtr, size_t size) {
            ^
/tmp/MWCudaMemoryFunctions.hpp-96bc82.hip:13:13: note: previous declaration is here
cudaError_t mwCudaMalloc(MWType_** devPtr, size_t size) {

```

Is there a way to "guide" hipify down the correct branch?

**Comment by twaters** [comment]
Note that I'm using an older version of rocm/hipify (4.3.1) - perhaps this has been resolved in newer releases.

**Comment by emankov** [comment]
Hello @twaters,

The aim of hipify-clang is to hipify AMAP, thus it uses a different preprocessor behaviour by default, when all conditional preprocessor blocks are taken into account.

To enable default C/C++ preprocessor behaviour, when undefined conditional blocks are skipped, please use the hipify-clang option `--skip-excluded-preprocessor-conditional-blocks`.  Since hipify-clang 5.6.0, you may use the synonym `--default-preprocessor`.

Btw, hipify-clang is a standalone tool independent of ROCm HIP, so you are not obliged to use the same hipify-clang version as ROCm HIP has. You can always use the newer version instead.

**Comment by twaters** [comment]
Thank you, that was extremely helpful!

**Comment by twaters** [comment]
Thank you @emankov, that was extremely helpful.
